### ISSUE TITLE
greenlight without docker: invalid return slack.rb line 29

### ISSUE THREAD

**Issue by zenny** [bigbluebutton/greenlight#190] opened 2017-10-10 09:03 UTC
Hi,

I am following http://docs.bigbluebutton.org/install/green-light.html#installing-greenlight-without-docker

At step 10, it is advised to migrate database by executing 'RAILS_ENV=production rake db:migrate'.

The output was with/out the SLACK part commented remained the same as of below:

```
# RAILS_ENV=production rake db:migrate --trace                                                                                                                                                            [92/1779]
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
SyntaxError: /root/greenlight/config/initializers/slack.rb:29: Invalid return
/root/greenlight/config/initializers/slack.rb
Tasks: TOP => db:migrate => environment
```

How to overcome this situation?

Cheers,
/z

**Comment by joshua-arts** [comment] 2017-10-10 13:46
Hey @zenny,

Are you trying to configure slack notifications? What does your `.env` file look like?

I can't seem to replicate the issue. GreenLight was designed to run with Docker, if it's possible to use Docker I would highly suggest so!

**Comment by zenny** [comment] 2017-10-10 18:02
Thanks @joshua-arts, I read somewhere a reply by @ffdixon to googlegroups mailinglist in which he recommended dockerless installation if one needs to customize greenlight. And I have never beeen comfortable with docker at any point of time in view of security (prefer FreeBSD jail). You can call me paranoid! ;-)

However, please find below the .env in which I am neither using OAuth with googledev nor twitter nor integrated with slack (I prefer mattermost):

```
$ cat /root/greenlight/.env
# This is a sample of the environment variables you will need
# To use, copy this file to .env `cp sample.env .env`

# Create a secret key for rails
#
# You can generate a secure one through the Greenlight docker image
# with with the command
#
#   docker run --rm bigbluebutton/greenlight rake secret
# 'sudo rake secret' inside greenlight directory for dockerless installation
SECRET_KEY_BASE=<SECRET_FROM_sudo_rake_secret_INSIDE_greenlight_directory>

# For either developent or production

# Enter credentials for your BigBlueButton Server
#
# The endpoint and secret from your bigbluebutton server.  To get these values, run
# the following command on your BigBlueButton server
#
#    bbb-conf --secret
#
# and uncomment the following two variables
BIGBLUEBUTTON_ENDPOINT=https://bbb.DOMAIN.TLD/bigbluebutton
BIGBLUEBUTTON_SECRET=<bbb-conf_--secret_OUTPUT>

# Twitter Login Provider (optional)
#
#   You will need to register the app at https://apps.twitter.com/
#   For the callback URL use 'http://<your hostname:port>/auth/twitter/callback'
#   Once registered copy the ID and Secret here
#
TWITTER_ID=
TWITTER_SECRET=

# Google Login Provider (optional)
#
#   You will need to register for at https://console.developers.google.com/apis/credentials
#   Select Oauth client ID -> web application
#   You will need to register for at https://console.developers.google.com/apis/credentials
#   Select Oauth client ID -> web application
#   For the callback URL use 'http://<your hostname:port>/auth/google/callback'
#   Once registered copy the ID and Secret here
#
#   The GOOGLE_OAUTH2_HD variable is used to limit sign-in to a particular Google Apps hosted domain. This
#   can be a string such as, 'domain.com'. If left blank, GreenLight will allow sign-in from all Google Apps hosted
#   domains.
#
GOOGLE_OAUTH2_ID=
GOOGLE_OAUTH2_SECRET=
GOOGLE_OAUTH2_HD=

# LDAP Login Provider (optional)
#
#   You can enable LDAP authentication by providing values for the variables below.
#   For information about setting up LDAP, see:
#     http://docs.bigbluebutton.org/install/green-light.html#ldap-oauth
#
LDAP_SERVER=
LDAP_PORT=
LDAP_METHOD=
LDAP_UID=
LDAP_BASE=
LDAP_BIND_DN=
LDAP_PASSWORD=

# If "true", GreenLight will register a webhook callback for each meeting
# created. This callback is called for all events that happen in the meeting,
# including the processing of its recording. These events are used to update
# the web page dynamically as things happen in the server.
# If not "true", the application will add a metadata to the meetings with this same
# callback URL. Scripts can then be added to BigBlueButton to call this callback
# URL and send specific events to GreenLight (e.g. a post publish script to warn   
# the application when recordings are done).   
# GREENLIGHT_USE_WEBHOOKS=true

# Enable uploading to Youtube (optional)
                                              # Enable uploading to Youtube (optional)
#
#   When this is enabled, users will be able to directly upload their recordings
#   to Youtube. If you plan to enable this, you should follow the steps outlined
#   in our docs for setting up the Youtube data API.
#
#   http://docs.bigbluebutton.org/install/green-light.html#8-enabling-uploading-to-youtube-optional
#
ENABLE_YOUTUBE_UPLOADING=false

# Slack Integration (optional)
#
#   You will need to register an incoming-webhook for your slack channel
#   in order for GreenLight to post to it. You can do this by going
#   to https://slack.com/apps/A0F7XDUAZ-incoming-webhooks, selecting your
#   team and then selecting "Add Incoming WebHooks integration" on the
#   desired channel. You will then need to paste the webhook below.
#
#SLACK_WEBHOOK=
#SLACK_CHANNEL=

# Landing Background (optional)
#
#   Supply a URL to an image to change the landing background. If no
#   URL is provided GreenLight will use a default image. If you
#   supply a path that does not lead to an image, no landing image
#   will appear.
#
LANDING_BACKGROUND=

# SMTP Mailer (optional)
#
GREENLIGHT_MAIL_NOTIFICATIONS=true
# In the format [localhost.localdomain]
GREENLIGHT_DOMAIN=bbb.DOMAIN.TLD
SMTP_FROM=USERNAME@gmail.com
SMTP_SERVER=smtp.gmail.com
SMTP_PORT=587 
SMTP_DOMAIN=gmail.com
SMTP_USERNAME=USERNAME@gmail.com
SMTP_PASSWORD=<GMAIL_PASSWORD>
SMTP_TLS=true
# SMTP_AUTH=login
# SMTP_STARTTLS_AUTO=true

# Enable QR Code generation (optional)
#
#   When this is enabled, users will be able to generate a QR code for direct access
#   to a meeting room that can be shared as the URL link.
#
ENABLE_QRCODE_GENERATION=false


# Prefix for the application's root URL
# Useful for deploying the application to a subdirectory
# Prefix for the application's root URL
# Useful for deploying the application to a subdirectory
#
#   default is '/b' (recommended)
#
RELATIVE_URL_ROOT=/b

# Uncomment and set to 'true' to only allow users to create meetings when authenticated.
# Unauthenticated users are still able to join meetings through invites.
# DISABLE_GUEST_ACCESS=false

# Comment this out to send logs to STDOUT in production instead of log/production.log .
DISABLE_RAILS_LOG_TO_STDOUT=true
```

I am not a ruby guy, so could not figure out exactly what does that error mean?!

**Comment by joshua-arts** [comment] 2017-10-10 18:12
@ffdixon is right. If you're going to be customising GreenLight it's probably better to not use Docker (unless you are comfortable rebuilding and deploying a new image).

You shouldn't be commenting out the `SLACK_WEBHOOK` and `SLACK_CHANNEL` environment variables (even if they are blank). Could you try uncommenting them and restarting the GreenLight server?

**Comment by zenny** [comment] 2017-10-10 18:15
@joshua-arts, I had the same results both with or without commenting out SLACK_WEBHOOK and SLACK_CHANNEL variables as I stated in the the OT.

**Comment by joshua-arts** [comment] 2017-10-10 18:32
Hmm... I just did a fresh install on my local machine using master and didn't encounter any issues. You should leave the slack variables uncommented.

Can you make sure you've pulled the latest from master? Also, ensure you haven't accidentally edited the `config/initializers/slack.rb` file. It seems very odd that it's throwing a `SyntaxError`.

**Comment by zenny** [comment] 2017-10-10 18:36
The source is up-to-date.
```
~/greenlight# git pull
Already up-to-date.
```
I didn't make any changes to any files including config/initializers/slack.rb fyi.

**Comment by joshua-arts** [comment] 2017-10-10 19:41
Which version of ruby are you using?

**Comment by zenny** [comment] 2017-10-10 20:14
```
# ruby -v
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
```

BTW, when doing bundle install, I had to make changes to rails version to 2.3.1  in Gemfile as it was warning about the a lower version in the system than in the Gemfile (2.4.0).

No rvm was used, fyi.

**Comment by joshua-arts** [comment] 2017-10-10 20:25
Yup, that'll do it. GreenLight is currently using ruby 2.4.0. This means that is may (and does) use features of ruby that are not supported in earlier versions. You can't downgrade the version and still expect it to work.

If you change the version in the Gemfile back to 2.4.0 and install ruby 2.4.0 and run `bundle` you shouldn't encounter the error anymore. If you want to manage many versions of ruby (and quickly switch between them), I'd recommend using [rvm](https://rvm.io/).

Let me know if this works for you!

**Comment by zenny** [comment] 2017-10-11 08:53
Upgraded ruby to what has been recommended at https://gorails.com/setup/ubuntu/16.04#ruby-rvm, yet no go, but popped up other issues as follows:

```
root@webinar:~/greenlight# ruby -v
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]

root@webinar:~/greenlight# rails -v
Could not find proper version of railties (5.0.5) in any of the sources
Run `bundle install` to install missing gems.

root@webinar:~/greenlight# sudo bundle install
The latest bundler is 1.16.0.pre.3, but you are currently running 1.15.4.
To update, run `gem install bundler --pre`
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break
this application for all non-root users on this machine.
**Your Ruby version is 2.3.1, but your Gemfile specified 2.4.2**
```

**Comment by joshua-arts** [comment] 2017-10-11 14:03
It looks like you could have multiple versions of ruby installed now. You can use `which ruby` to find the path to the one you're using. GreenLight is still trying to use your old 2.3.1 install. You need to setup your system to use ruby 2.4.0 or greater.

Also, you shouldn't be running `bundle install` as root.

**Comment by joshua-arts** [comment] 2017-10-16 21:07
Closing this issue as it doesn't appear to be an issue with the GreenLight source.

**Closed by joshua-arts** 2017-10-16 21:07 UTC
