### ISSUE TITLE
Building and running Docker after update problem

### ISSUE THREAD

**Issue by kamykm** [bigbluebutton/greenlight#2318] opened 2020-11-29 12:59 UTC
Hello,
I hope someone will be able to advise about this situation. 
I was running an older version of Ruby with an older version of greenlight for quite a long time now. (Ruby 2.3 and greenlight in docker). 

In the past days, I was trying to do an update. In my struggle I have done the following:
1) pulled new changes
2) tried to run "bundle install" to discover that I need to update my Ruby version
3) Installed Ruby 2.5 and created a symbolic link for it (in addition I had to run "gem install bundler". Otherwise, I would see a bad Ruby version while running "bundle env", bundler tried to use old Ruby version)
4) Installed missing libpq-dev  and  apt-get install libsqlite3-dev  (no problem there)
5) Now "bundler install" is a success 
6) I tried to build the docker image running ./scripts/image_build.sh bigbluebutton/greenlight release-v2  
Due to this problem:
https://github.com/jekyll/jekyll/issues/7463  and possible solutions below
https://bundler.io/blog/2019/01/04/an-update-on-the-bundler-2-release.html
https://bundler.io/blog/2019/05/14/solutions-for-cant-find-gem-bundler-with-executable-bundle.html
I have done two things:
- add --no-cache --network host to "docker build" command in image_build.sh script 
- add ENV BUNDLER_VERSION=2.1.4 and  RUN gem install bundler:2.1.4  to Dockerfile
After that, the image build process is a success
7) Unfortunately during docker-compose up i get these errors

greenlight-v2 | curl: (52) Empty reply from server
greenlight-v2 | bundler: failed to load command: rake (/usr/src/app/vendor/bundle/ruby/2.5.0/bin/rake) Bundler::LockfileError: You must use Bundler 2 or greater with this lockfile. /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/lockfile_parser.rb:108:in `warn_for_outdated_bundler_version' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/lockfile_parser.rb:95:in `initialize' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:84:in `new' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:84:in `initialize' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/dsl.rb:218:in `new' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/dsl.rb:218:in `to_definition' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/dsl.rb:13:in `evaluate' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:35:in `build' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler.rb:135:in `definition' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler.rb:101:in `setup' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/setup.rb:20:in `<top (required)>' /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require' /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
greenlight-v2 | >>> Database initialization
greenlight-v2 | bundler: failed to load command: rake (/usr/src/app/vendor/bundle/ruby/2.5.0/bin/rake)
greenlight-v2 | Bundler::LockfileError: You must use Bundler 2 or greater with this lockfile.

As you can imagine i have read the whole internet :) about these issues - That is how I got this far.
I understand that this is more likely a setup issue but I am worried that I might lose my mind soon :/ 
Please be of assistance..
- how can I make Docker use the correct bundler during docker-compose up ?
- if you suggest creating this setup from the beginning please advise - how should current setup look like?
- have you come across this?

**Comment by farhatahmad** [comment] 2020-12-02 23:02
Whats the output of `cat Gemfile.lock`?

**Comment by kamykm** [comment] 2020-12-02 23:13
It is bundled with bundler 2.1.4 if this is what you are looking for


  tabler-rubygem!
  turbolinks (~> 5)
  tzinfo-data
  uglifier (>= 1.3.0)
  web-console (>= 3.3.0)
  webmock

BUNDLED WITH
   2.1.4

**Comment by farhatahmad** [comment] 2020-12-04 02:46
At this point, it might be easier to just install Greenlight from scratch on a clean server and then copy over your database from the old server to the new

**Comment by kamykm** [comment] 2020-12-04 08:12
Thank you for your response. I assume that this will not resolve anything. I believe the issue is that docker scripts are not ready for the newer version of bundler and I actually created Gemfile.lock with bundler 2.1.4. 

The issue can be reproduced like this:
1) ie. add a gem to the project and run bundle install (using bundler 2.1.4 in your local setup)
2) make a git push 
3) make a git pull on your server setup (where is an older version of bundler)
4) run bundler install, build image and so on (and discover that you need to update bundler to do all that)
5) update your ruby and bundler on the server and discover that there is a problem with Docker scripts that are not ready for this new setup. 

I assume that one should keep their Gemfile.lock in repository https://stackoverflow.com/questions/4151495/should-gemfile-lock-be-included-in-gitignore 

Temporarily I have resolved this issue by removing "BUNDLED WITH 2.1.4"  manually from Gemfile.lock just after git pull.

**Comment by farhatahmad** [comment] 2020-12-05 18:51
Glad you got it to work. Yeah we don't include the `BUNDLED WITH` line in the Gemfile due to some reason I can't remember. Going to close this now - thank you for sharing the steps to reproduce and fix

**Closed by farhatahmad** 2020-12-05 18:51 UTC
