### ISSUE TITLE
error 500 when open profile

### ISSUE THREAD

**Issue by 1992pfr** [bigbluebutton/greenlight#1391] opened 2020-04-24 13:50 UTC
Hi,
i received a 500 error when i open my profile and also when i try to editing a user with the admin account:
in the production logs a the following lines:

```
INFO: [ce377a31-2155-4e6e-b5dd-37957a3de75d] method=GET path=/b/u/gl-zycdpkcyknzw/edit format=html controller=UsersController action=edit status=500 error='ActionView::Template::Error: undefined method `[]' for nil:NilClass' duration=169.33 view=0.00 db=30.34 host=greenlight
FATAL: [ce377a31-2155-4e6e-b5dd-37957a3de75d]
FATAL: [ce377a31-2155-4e6e-b5dd-37957a3de75d] ActionView::Template::Error (undefined method `[]' for nil:NilClass):
FATAL: [ce377a31-2155-4e6e-b5dd-37957a3de75d]     36:     <%= f.text_field :provider, class: "form-control", readonly: "" %>
[ce377a31-2155-4e6e-b5dd-37957a3de75d]     37:     <br>
[ce377a31-2155-4e6e-b5dd-37957a3de75d]     38:     <%= f.label t("settings.account.language"), class: "form-label" %>
[ce377a31-2155-4e6e-b5dd-37957a3de75d]     39:     <%= f.select :language, language_options, {}, { class: "form-control custom-select" } %>
[ce377a31-2155-4e6e-b5dd-37957a3de75d]     40:
[ce377a31-2155-4e6e-b5dd-37957a3de75d]     41:     <% current_user_role = current_user.highest_priority_role %>
[ce377a31-2155-4e6e-b5dd-37957a3de75d]     42:     <br>
FATAL: [ce377a31-2155-4e6e-b5dd-37957a3de75d]
FATAL: [ce377a31-2155-4e6e-b5dd-37957a3de75d] app/helpers/users_helper.rb:50:in `block in language_options'
[ce377a31-2155-4e6e-b5dd-37957a3de75d] app/helpers/users_helper.rb:48:in `each'
[ce377a31-2155-4e6e-b5dd-37957a3de75d] app/helpers/users_helper.rb:48:in `language_options'
[ce377a31-2155-4e6e-b5dd-37957a3de75d] app/views/users/components/_account.html.erb:39:in `block in _app_views_users_components__account_html_erb__36759021702131596_47382072462060'
[ce377a31-2155-4e6e-b5dd-37957a3de75d] app/views/users/components/_account.html.erb:16:in `_app_views_users_components__account_html_erb__36759021702131596_47382072462060'
[ce377a31-2155-4e6e-b5dd-37957a3de75d] app/views/users/components/_setting_view.html.erb:24:in `block in _app_views_users_components__setting_view_html_erb___2220923522083432153_47382095435780'
[ce377a31-2155-4e6e-b5dd-37957a3de75d] app/views/users/components/_setting_view.html.erb:16:in `_app_views_users_components__setting_view_html_erb___2220923522083432153_47382095435780'
[ce377a31-2155-4e6e-b5dd-37957a3de75d] app/views/users/edit.html.erb:32:in `_app_views_users_edit_html_erb__3268023940542289191_47382092802340'
INFO: [ce377a31-2155-4e6e-b5dd-37957a3de75d] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 duration=27.78 view=22.65 db=0.07 host=greenlight
```

**Comment by ByteHamster** [comment] 2020-04-24 22:13
There is currently an issue in the `config/locales/hy.yml` file. Deleting that file and re-creating the container fixes the 500 errors.

Source: https://github.com/bigbluebutton/greenlight/issues/1357#issuecomment-617203504

**Comment by pajowu** [comment] 2020-04-24 22:14
Should be a duplicate of https://github.com/bigbluebutton/greenlight/issues/1337, fixed in https://github.com/bigbluebutton/greenlight/pull/1361

**Comment by 1992pfr** [comment] 2020-04-27 14:30
Hi, the Error exist anyway:

i use only 3 language files. (en, de, it) - the other files moved into a subfolder.

```
INFO: [0dcb48bf-c26a-4f14-b0fe-773faf2dca6e] method=GET path=/b/u/gl-zycdpkcyknzw/edit format=html controller=UsersController action=edit status=500 error='ActionView::Template::Error: undefined method `[]' for nil:NilClass' duration=15.23 view=0.00 db=1.74 host=greenlight
FATAL: [0dcb48bf-c26a-4f14-b0fe-773faf2dca6e]
FATAL: [0dcb48bf-c26a-4f14-b0fe-773faf2dca6e] ActionView::Template::Error (undefined method `[]' for nil:NilClass):
FATAL: [0dcb48bf-c26a-4f14-b0fe-773faf2dca6e]     36:     <%= f.text_field :provider, class: "form-control", readonly: "" %>
[0dcb48bf-c26a-4f14-b0fe-773faf2dca6e]     37:     <br>
[0dcb48bf-c26a-4f14-b0fe-773faf2dca6e]     38:     <%= f.label t("settings.account.language"), class: "form-label" %>
[0dcb48bf-c26a-4f14-b0fe-773faf2dca6e]     39:     <%= f.select :language, language_options, {}, { class: "form-control custom-select" } %>
[0dcb48bf-c26a-4f14-b0fe-773faf2dca6e]     40:
[0dcb48bf-c26a-4f14-b0fe-773faf2dca6e]     41:     <% current_user_role = current_user.highest_priority_role %>
[0dcb48bf-c26a-4f14-b0fe-773faf2dca6e]     42:     <br>
FATAL: [0dcb48bf-c26a-4f14-b0fe-773faf2dca6e]
FATAL: [0dcb48bf-c26a-4f14-b0fe-773faf2dca6e] app/helpers/users_helper.rb:50:in `block in language_options'
[0dcb48bf-c26a-4f14-b0fe-773faf2dca6e] app/helpers/users_helper.rb:48:in `each'
[0dcb48bf-c26a-4f14-b0fe-773faf2dca6e] app/helpers/users_helper.rb:48:in `language_options'
[0dcb48bf-c26a-4f14-b0fe-773faf2dca6e] app/views/users/components/_account.html.erb:39:in `block in _app_views_users_components__account_html_erb__471765466005880373_47238128158500'
[0dcb48bf-c26a-4f14-b0fe-773faf2dca6e] app/views/users/components/_account.html.erb:16:in `_app_views_users_components__account_html_erb__471765466005880373_47238128158500'
[0dcb48bf-c26a-4f14-b0fe-773faf2dca6e] app/views/users/components/_setting_view.html.erb:24:in `block in _app_views_users_components__setting_view_html_erb___4026289656877381537_47238109349880'
[0dcb48bf-c26a-4f14-b0fe-773faf2dca6e] app/views/users/components/_setting_view.html.erb:16:in `_app_views_users_components__setting_view_html_erb___4026289656877381537_47238109349880'
[0dcb48bf-c26a-4f14-b0fe-773faf2dca6e] app/views/users/edit.html.erb:32:in `_app_views_users_edit_html_erb___1437062471846031590_47238126963140'
INFO: [0dcb48bf-c26a-4f14-b0fe-773faf2dca6e] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 duration=19.73 view=14.96 db=0.08 host=greenlight
```

**Comment by farhatahmad** [comment] 2020-04-27 14:51
The locales folder is extremely sensitive so you can't create subfolders in it. If you move the subfolder out and restart Greenlight then it should be working

**Closed** 2020-04-28 15:18 UTC
