### ISSUE TITLE
Disable automatic creation of default startroom upon first user login (via ldap)

### ISSUE THREAD

**Issue by simonschweizer** [bigbluebutton/greenlight#1146] opened 2020-04-01 07:19 UTC
In our university setting we are using BBB for online teaching during corona virus crisis. 

For authentication we use an ldap directory for our users (even for viewers), and import their account data (like first- and lastname). Once the account is verified against ldap the user can login successfully. However, as described in issue #1067 a default room is created for every unprivileged user on first login.

Detailed explanation: We have to discriminate students from tutors, teachers, faculty admins and super admins. This mostly works fine, except that after a few days already 350 start rooms are unused by students (they shall not spawn/use their own rooms, but only enter lecture / course rooms). From our perspective it seems that the amount of so many unused rooms is quite a waste of resources and spams the administrative views a lot!

We would like to support in shaping an enhancement/PR to provide BBB (Greenlight) with a config option for administrators to avoid the situation as described above.

Please consider the idea behind this as a feature request to further improve the already excellent BBB system concepts.

**Comment by rzo1** [comment] 2020-04-01 07:20
+1

**Comment by farhatahmad** [comment] 2020-04-01 14:05
Hi @simonschweizer 

Thanks for the request. It's a bit of a complicated issue as the answer to this is not as straight forward as it seems. Before I can answer, I need to know how you are enforcing the students to not spawn/use their own rooms? Is it throught the permission on the role? or through a site setting?

**Comment by simonschweizer** [comment] 2020-04-02 10:56
Hi @farhatahmad ,

Thanks for your fast answer. We are using the role permissions (like in the screenshot below) to prevent users from creating rooms (and with this also to use their home room, which can't be seen or started).

![image](https://user-images.githubusercontent.com/5512013/78241831-50c87700-74e1-11ea-85c7-ea5196ced2ef.png)


Generally, the creation of rooms is possible (e.g. if a user has the role teacher) and intended. But in our case, students, who are not allowed to even see their home room have one, so the list of server rooms in the organization page is quite large.

If the automatic creation can't be disabled, maybe it would be possible to hide them when implementing #1147?

**Comment by farhatahmad** [comment] 2020-04-02 15:44
> If the automatic creation can't be disabled, maybe it would be possible to hide them when implementing

Kind of what I was thinking. It would be best to try to avoid creating/deleting rooms based on whether the permission was created.

**Comment by SubjectXXX** [comment] 2020-04-03 06:35
Would like to see this feature also.

**Comment by gabrielestella** [comment] 2020-04-12 10:42
> In our university setting we are using BBB for online teaching during corona virus crisis.
> 
> For authentication we use an ldap directory for our users (even for viewers), and import their account data (like first- and lastname). Once the account is verified against ldap the user can login successfully. However, as described in issue #1067 a default room is created for every unprivileged user on first login.
> 
> Detailed explanation: We have to discriminate students from tutors, teachers, faculty admins and super admins. This mostly works fine, except that after a few days already 350 start rooms are unused by students (they shall not spawn/use their own rooms, but only enter lecture / course rooms). From our perspective it seems that the amount of so many unused rooms is quite a waste of resources and spams the administrative views a lot!
> 
> We would like to support in shaping an enhancement/PR to provide BBB (Greenlight) with a config option for administrators to avoid the situation as described above.
> 
> Please consider the idea behind this as a feature request to further improve the already excellent BBB system concepts.

I would like to see this feature too. Could be good delete the default room.

**Comment by mrkeksi** [comment] 2020-05-24 17:15
Fixed in new version as I see it.  

Can be closed

**Closed** 2020-05-27 15:07 UTC
Labels: feature request

**Comment by Schmidie64** [comment] 2020-05-28 06:51
Since the problem is solved now, it would be nice if I could delete the unnecessary startrooms. Is there an idea for this? Perhaps via the database (if via the database how do you do it best :)

**Comment by farhatahmad** [comment] 2020-05-28 14:01
For those looking for a way to delete rooms for users that were created before the new release, see: 
https://docs.bigbluebutton.org/greenlight/gl-admin.html#removing-rooms-from-users-who-cant-create-rooms

**Comment by rzo1** [comment] 2020-05-28 14:09
This throws an exception:

```
root@bbb:~# docker exec greenlight-v2 bundle exec rake room:remove["true"]
rake aborted!
ActiveRecord::StatementInvalid: PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: ...= $1 AND "role_permissions"."value" = $2 ORDER BY "roles"."p...
                                                             ^
: SELECT DISTINCT "roles"."name" FROM "roles" LEFT OUTER JOIN "role_permissions" ON "role_permissions"."role_id" = "roles"."id" WHERE "role_permissions"."name" = $1 AND "role_permissions"."value" = $2 ORDER BY "roles"."priority" ASC
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/postgresql_adapter.rb:677:in `prepare'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/postgresql_adapter.rb:677:in `block in prepare_statement'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `prepare_statement'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/postgresql_adapter.rb:617:in `exec_cache'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/postgresql_adapter.rb:600:in `execute_and_clear'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:81:in `exec_query'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:482:in `select_prepared'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:68:in `select_all'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/query_cache.rb:106:in `select_all'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/relation/calculations.rb:197:in `block in pluck'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/relation.rb:584:in `skip_query_cache_if_necessary'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/relation/calculations.rb:197:in `pluck'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/relation/calculations.rb:192:in `pluck'
/usr/src/app/lib/tasks/room.rake:8:in `block (2 levels) in <top (required)>'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'

Caused by:
PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: ...= $1 AND "role_permissions"."value" = $2 ORDER BY "roles"."p...
                                                             ^
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/postgresql_adapter.rb:677:in `prepare'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/postgresql_adapter.rb:677:in `block in prepare_statement'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `prepare_statement'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/postgresql_adapter.rb:617:in `exec_cache'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/postgresql_adapter.rb:600:in `execute_and_clear'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:81:in `exec_query'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:482:in `select_prepared'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:68:in `select_all'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/query_cache.rb:106:in `select_all'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/relation/calculations.rb:197:in `block in pluck'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/relation.rb:584:in `skip_query_cache_if_necessary'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/relation/calculations.rb:197:in `pluck'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/relation/calculations.rb:192:in `pluck'
/usr/src/app/lib/tasks/room.rake:8:in `block (2 levels) in <top (required)>'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => room:remove
(See full trace by running task with --trace)

```

**Comment by farhatahmad** [comment] 2020-05-28 14:46
Good old Postgres. Can you create a new issue for it please?

**Comment by rzo1** [comment] 2020-05-28 17:02
> Good old Postgres. Can you create a new issue for it please?

Done, https://github.com/bigbluebutton/greenlight/issues/1693
