### ISSUE TITLE
"Require Authentication for Rooms" - Back door old room settings

### ISSUE THREAD

**Issue by rubinturbo** [bigbluebutton/greenlight#1949] opened 2020-07-29 08:24 UTC
Greenlight v2.6.5

Scenario:

- Room with "Require Authentication for Rooms = OFF"
- Other user open room start page without login - User is able to enter the room
- Edit room setting "Require Authentication for Rooms = ON"
- Other user can still enter the room without login if he does not reload the page => BUG
- ... if the user make a site reload the login requirement is shown

**Comment by farhatahmad** [comment] 2020-07-29 13:36
Thanks for reporting this. We could probably add an additional check in the controller for the join

**Comment by KH-Amir-TN** [comment] 2021-12-15 20:24
Hi, this is Amir the new Greenlight maintainer.
Could you please give me a clear scenario to reproduce.
I've tried:
**Scenario 1:**
1. Creating a room with  the 'Anyone can start' option.
2. Disabling the 'Require Authentication for Rooms' Site setting.
3. Accessing the room in another browser session without being authenticated.
4. Enabling the  'Require Authentication for Rooms' Site setting.
5. Clicking the start button.

**Scenario 2:**
1. Creating a room without the 'Anyone can start' option.
2. Starting the room session.
3. Disabling the 'Require Authentication for Rooms' Site setting.
4. Accessing the room in another browser session without being authenticated.
5. Enabling the  'Require Authentication for Rooms' Site setting.
6. Clicking the join button.

**Scenario 3:**
1. Creating a room without the 'Anyone can start' option.
2. Disabling the 'Require Authentication for Rooms' Site setting.
3. Accessing the room in another browser session without being authenticated.
4. Clicking the join button.
5. Waiting for the session to start.
6. Enabling the 'Require Authentication for Rooms' Site setting.
7. Starting the session.

In all scenarios and in versions [2.6.5](https://github.com/bigbluebutton/greenlight/tree/release-2.6.5) and the [master](https://github.com/KH-Amir-TN/greenlight) Greenlight behavior was the redirection to the home page and the showing of the fallowing alert banner: 
![image](https://user-images.githubusercontent.com/29759616/146259431-70bfdbbb-0cee-4add-b0c3-6a5154917ac3.png)
I believe that I am missing something.

Amir,

**Comment by KH-Amir-TN** [comment] 2022-01-15 15:22
Hi @rubinturbo,
Since your issue has been **tested in three different scenarios** according to your description of the case **without having the outcome that you've mentioned** and because I requested you to further provide details on your issue that it seems it was fixed in later updates.
**I'll close this issue with a conclusion that it has been fixed.**
Please reopen it if you believe that it's hasn't.

**Closed** 2022-01-15 15:22 UTC
Labels: bug
