### ISSUE TITLE
sorting of rooms 

### ISSUE THREAD

**Issue by kinimodmeyer** [bigbluebutton/greenlight#1706] opened 2020-05-29 19:21 UTC
hello,

i updated yesterday to 2.6.1.
the room list is not sorted by the "creation date" anymore.
maybe it is a feature that running is now on top but i think we should add
a second sort on "creation date" or a explicit column which then could be sorted.

**Comment by elemhsb** [comment] 2020-05-30 22:51
Hi,
a second issue here  51824ad84b398a8c1f5094427f40ab4b68ad33ed is
if "no" room is running the sorting of other columns like name, id, etc. is not working.
btw. in this case  you will see the creating history. ;-)

**Comment by farhatahmad** [comment] 2020-06-01 14:24
Hi @kinimodmeyer,

This is expected behaviour based on requests made #1147. Based on what the majority of users said, sorting by creation date wasn't really useful. To allow sorting on creation date we would need to either give it it's own column or revert the default back to sorted by date with the option to sort by status

@elemhsb Please open a separate issue for that.

**Comment by Sea444** [comment] 2020-06-01 21:38
Since 2.6 I can no longer detect any logical default sorting of the rooms.
I would suggest that by default the rooms should be sorted by the end time of the last conference. This would be the most logical from my point of view:
Active conferences are up.
Conferences that are no longer active then slide down.

**Comment by kinimodmeyer** [comment] 2020-06-02 07:02
i think we mixing the issues here a little bit. i think there are topics "we" could working on:

1. we could invent a new column to manually sort for the creation date
2. we should always apply a second sort column to not mix rows in the same sort. (like state). on sort state the second column could your mentioned activity on the other columns maybe the date-created.

@farhatahmad i looked at the code and i seemed a little a manual sorting. just want to say that you could do the status + secondary sort with raw sql with FIELD like: `SELECT * FROM `rooms` ORDER BY FIELD(`status`, "muh", "muh2" ...), `date_created` ASC ` :)

**Comment by farhatahmad** [comment] 2020-06-02 14:12
I'm still trying to think of what the best way to sort the rooms is. Since we no longer display the creation date for rooms with sessions, we can't sort only by creation date (since it'll end up looking weird for the user). My current thought is: 
- Default sort is by creation and last session date. If you look at Server Rooms now, some rooms have "Created:" and some rooms have "Ended:". This sort will display them in order based on that date
- Optional sort by Active column which will display the active rooms first

**Comment by Sea444** [comment] 2020-06-03 09:07
Actual:
room name | user | room id | participant number | status
(2nd line to room name: start date (when active) OR end date OR create date)

Suggestion:
room name | user | create date | start date (when active) OR last end date | participant number | status
(2nd line to room name: room ID)

I think it is not important to be able to sort by ID. But it is useful to be able sort by create date and last end date

**Comment by Sea444** [comment] 2020-06-03 09:17
Actual:
room name | user | room id | participant number | status
(2nd line to room name: start date (when active) OR end date OR create date)

Suggestion:
room name | user | create date | last active date | participant number | status
(2nd line to room name: room ID) (2nd line to status: last start date: "since")

last active date
-> for active rooms=now
-> for inactive rooms=last end date

I think it is not important to be able to sort by ID. But it is useful to be able sort by create date and last active date

Default sort:

1. by last start date (newest on top)
2. by create date

**Comment by EmmyGraugans** [comment] 2020-06-29 11:35
> * Default sort is by creation and last session date. If you look at Server Rooms now, some rooms have "Created:" and some rooms have "Ended:". This sort will display them in order based on that date

This sounds useful - actually "Sort by whatever date is most recent" - so: 
- Date-Created for rooms that were never started
- Date-Ended for rooms that were started at least once
- Date-Started for rooms that are currently running

(Alternatively have all running rooms on top, but still sorted by "Date-Started".

**Comment by farhatahmad** [comment] 2020-07-29 15:04
Fixed in 2.7

**Closed by farhatahmad** 2020-07-29 15:04 UTC
Labels: enhancement, v2.7
