### ISSUE TITLE
desktop notifications shows 3 times when joining someone elses room

### ISSUE THREAD

**Issue by zach-chai** [bigbluebutton/greenlight#88] opened 2017-01-20 23:44 UTC

**Comment by ffdixon** [comment] 2017-01-20 23:46
Here's a screen shot of what the user sees.

![triple](https://cloud.githubusercontent.com/assets/290351/22169258/c9b943ea-df40-11e6-9f4a-e401ebcddabb.png)

**Comment by zach-chai** [comment] 2017-02-16 22:38
I think this happens if you have multiple greenlight tabs open

**Comment by joshua-arts** [comment] 2017-10-12 18:53
This was caused by having multiple tabs open. It has since been fixed in this commit: 1644358. Now having multiple tabs open will result in one notification.

**Closed by joshua-arts** 2017-10-12 18:53 UTC
