### ISSUE TITLE
Meeting title "a&b" throws exception

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/greenlight#157] opened 2017-03-26 15:43 UTC
We need to restrict meeting titles from containing the letter '&' as it causes an exception within GreenLight when creating/joining the meeting.

Mar 26 11:40:50 greenlight-demo 50438955b70b: I, [2017-03-26T15:40:50.905906 #1]  INFO -- : [1e4c98dd-5bf2-46dd-a727-0b4221a9b3e1] method=GET path=/b/meetings/a%26b/join format=json controller=BbbController action=join status=500 error='BigBlueButton::BigBlueButtonException: Impossible to convert XML to hash. Error: #<RuntimeError: Illegal character '&' in raw string "a&b">

**Comment by joshua-arts** [comment] 2017-10-20 20:21
Closing as this issue was left open because the fix was implemented as temporary. However, it is now the expected behaviour.

**Closed by joshua-arts** 2017-10-20 20:21 UTC
