### ISSUE TITLE
Load Greenlight landing page very slow in Internet Explorer 11 or Edge

### ISSUE THREAD

**Issue by fungma** [bigbluebutton/greenlight#265] opened 2018-09-13 16:05 UTC
Server and Client in Guangzhou, China
Server: Bigbluebutton 2.0 rc5 , Greenlight 2
Client PC: Windows 10 ver 1803 

Chrome or Firefox load the Greenlight landing page about 1 second.
But Internet Explorer 11/Edge, loading Greenlight page time is ONE MINUTE!

May be the performance problem is coursed by using Google Fonts in the Greenlight landing page?

Reference resources
https://wordpress.org/plugins/disable-google-fonts/
https://github.com/dimadin/disable-google-fonts

**Comment by jiama843** [comment] 2018-09-17 20:15
Hi @fungma,

Is the same lag occurring when you try to access the demo/other servers on IE11/Edge, or is it only happening on your server?

**Comment by fungma** [comment] 2018-09-19 11:59
> Hi @fungma,
> 
> Is the same lag occurring when you try to access the demo/other servers on IE11/Edge, or is it only happening on your server?

Yes, the same.

From Guangzhou, China 
ISP : China Telecom

IE11 / Edge load page https://demo.bigbluebutton.org/gl  about 64 seconds.
same pc, Chrome/Firefox load https://demo.bigbluebutton.org/gl about 3 seconds.

**Comment by jfederico** [comment] 2018-10-04 15:07
The main issue here seems to be that as the fonts are external to the application, they sometimes can not be downloaded. One option to solve this problem may be to bundle them as part of Greenlight, but that would cause the repo to grow really big.

As we are not able to reproduce it and the requster hasn't come back to us, I am going to put this on hold for a week before closing it as "won't fix" unless we hear back from @fungma

**Closed** 2018-10-12 19:11 UTC
Labels: bug, on hold

**Comment by fungma** [comment] 2018-10-16 01:43
Sorry for late reply.

Same problem.
the fonts is integrated in Chrome/Firefox ?
but not integrated in IE /Edge
Because the  fuck Great Firewall，From China , fetch Google fonts is very slow.

So, would you please remove using the external fonts? or have some feature to disable it.
