### ISSUE TITLE
Preupload is not possible while a conference is running

### ISSUE THREAD

**Issue by uscreen-daniel** [bigbluebutton/greenlight#2188] opened 2020-10-12 12:59 UTC
Preupload of a presentation is only possible if you close the conference for all. If you are the person in the conference and you leave it, the conference is still open. You could upload a new presentation and you will get a "success", but the presentation ist not shown. 

Would be great to fix it, or to show the uploader an information, that the conference is running and no uploads are not possible.

**Comment by farhatahmad** [comment] 2020-10-13 19:25
This is kind of part of #2008. Currently, settings and presentations are applied at the start of the meeting, and changing them while a meeting is running means that it could cause some inconsistencies

**Comment by farhatahmad** [comment] 2021-05-19 21:39
Going to close this as a duplicate of #2008

**Closed by farhatahmad** 2021-05-19 21:39 UTC
Labels: feature request
