### ISSUE TITLE
Cannot sort server rooms by status

### ISSUE THREAD

**Issue by myymi** [bigbluebutton/greenlight#1044] opened 2020-03-20 10:32 UTC
Admins cannot sort server rooms by status. It's usability issue, as all other columns are sortable but this. Also, you cannot tell the difference visually between sortable and unsortable columns.

**Comment by farhatahmad** [comment] 2020-03-20 12:58
Hi @myymi,

Yes this is by design (due to the BigBlueButton API), but I agree a sortable icon beside the sortable columns would improve the user experience

**Comment by ljoets** [comment] 2020-03-26 11:01
Yes, it could be a useful enhancement.

**Comment by mbile** [comment] 2020-04-25 11:29
Yes, It would have been an amazing feature if we could sort out the status of server rooms so that we can monitor the running meetings.

**Comment by farhatahmad** [comment] 2020-05-27 15:06
Fixed in v2.6

**Closed by farhatahmad** 2020-05-27 15:06 UTC
Labels: enhancement
