### ISSUE TITLE
shared room recording problem in version 2.7.1 

### ISSUE THREAD

**Issue by MortezaTaghaddomi99** [bigbluebutton/greenlight#2015] opened 2020-08-15 06:54 UTC
in this version, only if the room owner starts a room, the recording button in BBB is available. 
If a person, that the room is shared with him starts the meeting, the recording button isn't available. 
I read greenlight 2.7 changes logs, and I think this isn't part of new features but it might be considered as a bug. 

Note: "Allow room to be recorded" was set to "always enable"

**Comment by lonesomewalker** [comment] 2020-08-21 07:27
This might corelate to my issue, which i posted in bbb/bbb:
https://github.com/bigbluebutton/bigbluebutton/issues/10222

But we even have in new rooms not the possibility to record :-(

**Comment by MortezaTaghaddomi99** [comment] 2020-08-27 09:37
I had to revert this version to 2.6 quickly at that moment. I can't produce the bug now but I think it about this feature: 

> Added the ability to allow room owners to specify whether they want the room recorded or no

I'd switched some of the new features in site setting. (recording was enabled if the owner starts the room)

**Comment by BenSjoberg** [comment] 2020-08-28 13:42
"Allow room to be recorded" doesn't appear unless "Require Room Owner and Joiner Consent to Recording" is enabled. Is that a bug? It seems like one to me because those settings seem unrelated.

**Comment by aozalevsky** [comment] 2020-09-02 06:37
I have a similar issue. In my case, I have 'Allow any user to start this meeting' and 'All users join as moderators'. The record button appears only if the owner (in my case he is also an administrator) starts the room. If the room is started by the anonymous moderator no record button at all. The 2.6 behavior was more convenient.

**Comment by farhatahmad** [comment] 2020-09-02 14:14
@aozalevsky Thanks for the information. I've been able to reproduce this and should hopefully have it fixed in the next version

**Closed** 2020-09-02 17:55 UTC
Labels: bug, v2.7.3
