### ISSUE TITLE
Feature request: Add links "Privacy policy" and "Imprint" to footer

### ISSUE THREAD

**Issue by Sea444** [bigbluebutton/greenlight#1268] opened 2020-04-11 12:53 UTC
**What is missing:**
- Privacy policy
- Imprint

**Desire/implementation proposal:**
- Link "Privacy policy" in the footer (same ligne with footer/powered_by)
- Link "Imprint" in the footer (same ligne with footer/powered_by)
- Add entries in language file
- urls can be defined via the administration interface (similar to the link for the logo)
- if no url is defined, the link is not visible for users

**Example:** 
Provided by Greenlight. 2.5.2 | Privacy policy | Imprint

**Note:**
This information is mandatory in the European Union.

**Comment by farhatahmad** [comment] 2020-04-13 14:01
Hi @Sea444 

Thanks for creating this feature request. While I definitely agree with you, the problem is that we  haven't written up either of these files specifically for Greenlight. This means I can't include them until they get done. I'll leave this open as a feature request until we update it with atleast the Privacy Policy

**Comment by Sea444** [comment] 2020-04-15 21:56
Hi @farhatahmad 

I think there's been a misunderstanding. Just because there are no corresponding files in Greenlight included (yet), my suggestion is to include links to external (!) websites that contain this information. For example, if a school uses Greenlight, the school can simply link to the imprint of the school website and the privacy information of the school website. 

In my opinion, this would be a very simple solution to the problem in order to comply with legal requirements. It would be great if this could be included in the next update.


Footer:

![grafik](https://user-images.githubusercontent.com/63501663/79391925-bb15f880-7f72-11ea-8ca5-fe240a13267f.png)

Administration interface:

![grafik](https://user-images.githubusercontent.com/63501663/79393014-b4888080-7f74-11ea-8227-ca32d35f73be.png)

**Comment by einhirn** [comment] 2020-04-23 08:20
I'm taking a stab at this.

**Comment by farhatahmad** [comment] 2020-05-27 15:08
Fixed in v2.6

**Closed by farhatahmad** 2020-05-27 15:08 UTC
Labels: feature request
