### ISSUE TITLE
Thumbnail on hover is clipped for recordings at the bottom

### ISSUE THREAD

**Issue by zach-chai** [bigbluebutton/greenlight#64] opened 2016-12-01 22:32 UTC

**Comment by joshua-arts** [comment] 2017-10-12 15:34
I am unable to reproduce this issue in the latest version of GreenLight. It appears to be fixed, so I'll close this issue for now. If it proves to still be a problem we can reopen this issue in the future.

**Closed by joshua-arts** 2017-10-12 15:34 UTC
