### ISSUE TITLE
No automated email to reset passwords on user migration

### ISSUE THREAD

**Issue by bluecakey** [bigbluebutton/greenlight#4941] opened 2023-03-09 15:47 UTC
Hi,

I have a v2 and a v3 server running and when first migrating the users there was no working SMTP config on the v3 server so of course no emails were sent out.

Now with a working SMTP config (e.g. invitations get sent out) when re-running the migration or deleting a user and then re-migrating it, there's still no automated email to the user with the prompt to reset the password.

Thanks for the call today,
Nicola

**Comment by scouillard** [comment] 2023-03-09 16:59
Hi,

This is expected behaviour.

We decided not to send an email on migration so that system administrators can do the migration, test things out - and re-do the migration if needed - without sending an email to all the users every time.

As of right now, migrated users are expected to manually ask for a password reset via the login flow.

We are thinking of a way to streamline the reset password process upon migration.

A rake task that would send a reset password email to the migrated users on command seems to be the best solution.

Please feel free to share any suggestion.

Thank you very much for the feedback.

**Comment by bluecakey** [comment] 2023-03-10 07:53
Hey,

I agree that it's probably better to not have it as part of the user migration task.

I think having the option to send the email to all separately would be the smoothest way.
I would like to make the migration to v3 as easy as possible for our users.

**Comment by farhatahmad** [comment] 2023-03-21 21:15
Fixed in the latest release. See: https://docs.bigbluebutton.org/greenlight_v3/gl3-migration.html#after-the-migration

**Closed by farhatahmad** 2023-03-21 21:15 UTC

**Comment by bluecakey** [comment] 2023-03-31 13:37
Hi, I can't seem to find the "after the migration" part in the new docs. Is it possible it was missed when they changed?
