### ISSUE TITLE
v3.02 create/join commands are adding extra /, probably other calls as well,  

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/greenlight#5070] opened 2023-03-25 13:11 UTC
Installed GL V3.02,  noticed I could not connect to our load commercial loadbalancer.

Appears bbb-web does not care about the api//create api//join being sent.   Not sure if Scalelight is affected.

DOCKER LOG
request=https://xxxxxxxxx.distancelearning.cloud/bigbluebutton/api//create?guestPolicy=ALWAYS_ACCEPT docker logs

NGINX
172.20.0.4 - - [25/Mar/2023:12:59:18 +0000] "GET /bigbluebutton/api//create?guestPolicy=ALWAYS
67.251.12.251 - - [25/Mar/2023:12:59:18 +0000] "GET /bigbluebutton/api//join?createTime=1679749158535

**Comment by GhaziTriki** [comment] 2023-03-25 13:28
Hi @hostbbb 

It is related to this issue https://github.com/mconf/bigbluebutton-api-ruby

And I think it is also a duplicate of this one https://github.com/bigbluebutton/greenlight/issues/4924

**Comment by hostbbb** [comment] 2023-03-25 15:18
Thanks, i was able to hack the gem in the docker with that fix to get it working.  I did notice in the v3.02 we are using gem 'bigbluebutton-api-ruby', '1.8'

looks like the most current version in 1.9 in mconf git?

**Closed** 2023-04-04 16:03 UTC
