### ISSUE TITLE
New "room attribute"

### ISSUE THREAD

**Issue by tyl0re** [bigbluebutton/greenlight#2472] opened 2021-01-26 09:11 UTC
It would be good to have the Attribute
(Only Registered User/Anonymous User Allowed) per room

Class rooms only are only for Registered User (So they cant send the link to someone other, who disturbs the Curse)
A Meeting with the Parents should allow Anonymous Link since it would be a waste of time Register all Parents before, specially new Parents

If every User is registered it would be good, that they can only join (as non admin) shared rooms, when the Teacher is already there. So 
The User sees all His Class Rooms when he is logged in

**Comment by mrkeksi** [comment] 2021-01-26 14:43
we have set up an extra frontend that is only there for such purposes. Or there are days when you open the complete GL for "parents' evenings". But in the end I agree with you that this setting should also be made available to rooms.

**Comment by demlak** [comment] 2021-01-28 00:08
Duplicate of #1714

**Closed** 2021-01-28 01:15 UTC
