### ISSUE TITLE
updated 2.7 preuploading  returns 413 error

### ISSUE THREAD

**Issue by erpsolns** [bigbluebutton/greenlight#1972] opened 2020-08-02 03:05 UTC
When uploading 
ppt 35 pages 2.1MB returns 
413 Request Entity Too Large
nginx/1.10.3 (Ubuntu)
when preuploading

pdf 35 pages 3.2MB returns
413 Request Entity Too Large
nginx/1.10.3 (Ubuntu)
when preuploading

**Comment by hex-m** [comment] 2020-08-03 11:28
duplicate of #1973

**Closed** 2020-08-04 13:48 UTC
