### ISSUE TITLE
Error 500: (log: missing token / digest params)

### ISSUE THREAD

**Issue by alfonsolsl** [bigbluebutton/greenlight#2156] opened 2020-10-03 21:13 UTC
My client is trying to log in after we update to the last version of greenlight right now (oct 03). 

She was having issues with the resend verification code bug but now she has a error 500.

i'm thinking is her side and the browser cache but prefer to publish and be sure is nothing or if this can help to improve something.

```
ERROR: [7a442060-1c53-4c84-8642-70468ed2bc83] Support: ala***@gmail.com creation failed: User params are not valid.
INFO: [7a442060-1c53-4c84-8642-70468ed2bc83] method=POST path=/b/signup format=html controller=UsersController action=create status=200 duration=369.46 view=34.42 db=2.83 host=greenlight
INFO: [360348c9-17d1-4a22-9e76-d0c1b32b46d9] method=GET path=/b/signin format=html controller=SessionsController action=signin status=200 duration=32.13 view=23.06 db=1.20 host=greenlight
INFO: [171601d0-64fb-4363-99f8-5882e86b179a] Support: ala****@gmail.com is attempting to login.
INFO: [171601d0-64fb-4363-99f8-5882e86b179a] method=POST path=/b/u/login format=html controller=SessionsController action=create status=302 duration=312.36 view=0.00 db=3.82 location=https://ses******ama.com/b/account_activations host=greenlight
INFO: [498f9280-cdbc-4e63-b657-bc0117007bdb] method=GET path=/b/account_activations format=html controller=AccountActivationsController action=show status=500 error='RuntimeError: Missing token/digest params' duration=8.24 view=0.00 db=1.06 host=greenlight
FATAL: [498f9280-cdbc-4e63-b657-bc0117007bdb]
FATAL: [498f9280-cdbc-4e63-b657-bc0117007bdb] RuntimeError (Missing token/digest params):
FATAL: [498f9280-cdbc-4e63-b657-bc0117007bdb]
FATAL: [498f9280-cdbc-4e63-b657-bc0117007bdb] app/controllers/account_activations_controller.rb:68:in `find_user'
INFO: [498f9280-cdbc-4e63-b657-bc0117007bdb] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 duration=28.26 view=23.36 db=0.14 host=greenlight
```

**Comment by alfonsolsl** [comment] 2020-10-03 21:15
She log in and click to resend the verification code to email (she said nothing happens)
she tried to create a new account but she already had one.
the she try to log in and error 500 in the face.

i'm trying to reproduce and i can't.

**Comment by farhatahmad** [comment] 2020-10-05 20:02
Can't seem to reproduce this locally so I'm not quite sure how that happened. If the user is still having issues signing in, you can manually activate her account using the following commands
```
docker exec -it greenlight-v2 bundle exec rails c
User.find_by(email: "users_email").activate
```
Going to close this since I can't reproduce. Feel free to re-open it if you run into the issue again

**Closed by farhatahmad** 2020-10-05 20:02 UTC

**Comment by paulmenzel** [comment] 2020-10-24 11:51
As reported in https://github.com/bigbluebutton/greenlight/issues/2211 others are having this issue too. We are having it too.

Where should the missing token/digest params come from?

**Comment by paulmenzel** [comment] 2020-10-24 12:34
Looking through the changes of ``, commit 816cefe1b6 (Fixed 404 when resending verification email (#2110)) in merge/pull request https://github.com/bigbluebutton/greenlight/pull/2110 introduces the new error message, I assume it also introdced the regression.

The change is included since [release](https://github.com/bigbluebutton/greenlight/releases) 2.7.5 from September 23rd, 2020.

**Comment by paulmenzel** [comment] 2020-10-24 12:43
So, if somebody else than the user requests a new password for the email address, the user is routed through the account activation controller? That does not seem to be correct.

**Comment by paulmenzel** [comment] 2020-10-24 13:01
Reverting commit 816cefe (Fixed 404 when resending verification email (#2110)) gets rid of the 500 error, and then I am shown a message *Verify your email* (German: Verifizierung Ihrer E-Mail-Adresse) tell me, that my account wasn’t verified yet.

We set up BigBlueButton/Greenlight in March 2020 with no SMTP server settings. These were enabled just some days ago. Maybe results in unconsidered code paths.

**Comment by paulmenzel** [comment] 2020-10-24 13:19
In addition to configure SMTP, activating `ALLOW_MAIL_NOTIFICATIONS=true` seems to be the toggle causing havoc here.

@alfonsolsl, did you do similar configuration changes?

**Comment by alfonsolsl** [comment] 2020-10-24 13:23
I'm reading my own adopting process in your messages, was the same but I did not made the tracing of the error. 

Sounds like you find the culprit

**Comment by toehold** [comment] 2020-11-12 09:33
Has there been any progress on this issue? I also get this when resetting a user password! Using gl 2.7.8 with LDAP and gl authentication.
thanks

**Comment by paulmenzel** [comment] 2020-11-12 09:43
Please make sure if the user account is activated, or not.

**Comment by mgiammarco** [comment] 2020-12-01 15:54
I have the same problem. I have activated mail notification. Users created AFTER enabling mail notification are ok, they can start email reset procedure and they work correctly. Users created BEFORE enabling mail notification, when they ask to change password the cannot login anymore, with error 500.

**Comment by Mrhalix** [comment] 2020-12-02 15:19
Same problem here, first I faced error 404 when went through resend verification email process, then I found an issue here, told me to upgrade greenlight to the latest version and i did, then faced error 500.

**Comment by reesericci** [comment] 2020-12-24 01:42
Getting 500 still, on the latest version, manually activating users fixes the problem.

**Comment by bayden10** [comment] 2021-01-20 16:29
trying to re-activate the initial registered Admin does not fix this issue of 500. Could be reloaded to home room 3 and 4 code security.

**Comment by bayden10** [comment] 2021-02-12 16:30
My issue was related to Docker Swarm indicating old IPs and NETMAP-->DSTNAT rules. Talk about pulling hairs.. My issue is now Resolved.. I had to leave the Docker Swarm and adjust NETMAP to DST-NAT --> DSTNAT
