### ISSUE TITLE
Missing feature "ldap failover"

### ISSUE THREAD

**Issue by chillje** [bigbluebutton/greenlight#2535] opened 2021-02-16 09:45 UTC
Hi,
Iam missing support of an ldap failover. I tried to set my 2 ldap hosts in ".env" file like:
 * `LDAP_SERVER=ldap1 ldap2`
 * `LDAP_SERVER=ldap1, ldap2`
 * `LDAP_SERVER=ldap1; ldap2`

Every time I use multiple LDAP servers I get a 500 Error if I try to login to my greenlight instance. 

Am I missing something regarding the syntax or is an LDAP failover currently not supported?

Motivation: If one of the LDAP instances fails, the system can fall back on the other one.

Thank you and regards

**Comment by mrkeksi** [comment] 2021-02-16 12:53
It is not supportet right now. See: #2127
But u can setup an LDAP Server who can handle multiple LDAP destinations.

**Comment by chillje** [comment] 2021-02-16 13:20
Thank you for pointing me to the other issue. It seems my search strings were not ideal.

Your suggestion is a way to get around the problem of specifying both LDAP servers, right. But I would outsource the error potential to another service.
If several LDAP servers can be specified, I am not bound to only one service, but with an LDAP proxy I am, because the proxy itself can also fail.

**Comment by farhatahmad** [comment] 2021-02-18 22:30
As mentioned above, duplicate of #2127

**Closed** 2021-02-18 22:30 UTC
