### ISSUE TITLE
LDAP auth fails when user have jpegphoto image

### ISSUE THREAD

**Issue by romale** [bigbluebutton/greenlight#841] opened 2019-10-15 20:32 UTC
Today i've update my greenlight with
docker pull bigbluebutton/greenlight:v2
A current version is "Greenlight. 2.4-b2"
But users who have "jpegphoto: /9j/4AAQ...", those not empty, they can't login.
When user with jpegphoto try to login, i've this error:
```
INFO: [b5e2e9e7-a2e9-4795-89f5-fb4631b9f245] method=GET path=/b/ format=html controller=MainController action=index status=200 duration=21.89 view=17.00 db=0.51 host=greenlight
INFO: [c3440ee3-75d9-4e0c-9543-f5b48c10bf85] method=GET path=/b/signup format=html controller=SessionsController action=new status=200 duration=30.53 view=22.06 db=0.72 host=greenlight
INFO: [26b5a69a-22ce-431b-a961-af6b1f037b5f] method=GET path=/b/ldap_signin format=html controller=SessionsController action=ldap_signin status=200 duration=29.22 view=24.14 db=0.49 host=greenlight
ERROR: [12eb2d13-d61c-4a36-b9c9-399bb34be6c4] Support: Error authenticating via omniauth: "\xFF" from ASCII-8BIT to UTF-8
INFO: [12eb2d13-d61c-4a36-b9c9-399bb34be6c4] method=POST path=/b/auth/ldap format=html controller=SessionsController action=ldap status=302 duration=39.76 view=0.00 db=1.37 location=https://meet.example.com/b
/ host=greenlight
```
When I clear jpegphoto attribute, then user login success

**Comment by farhatahmad** [comment] 2019-10-17 19:48
Hi @romale, 

So I've tried to reproduce locally and I'm not having any

**Comment by farhatahmad** [comment] 2019-10-17 19:48
Closed by accident

**Comment by farhatahmad** [comment] 2020-01-20 19:03
I haven't been able to reproduce this anymore on master. @romale Can you confirm if this is still an issue after the release of 2.4?

**Comment by romale** [comment] 2020-01-21 10:40
Hi @farhatahmad , today i've update GL to "Greenlight. 2.4.1" (folowing up this guide http://docs.bigbluebutton.org/greenlight/gl-install.html#updating-greenlight), but the issue still exist, unfortunately.
I deleted the user (with jpegphoto), but I can not register him via ldap, but after `ipa user-mod USERNAME --setattr jpegphoto=''`, I can do it

**Comment by farhatahmad** [comment] 2020-01-21 16:40
@romale Thanks for giving it a try and responding back. I've finally been able to reproduce it, so I'll hopefully have it fixed in the next release

**Comment by romale** [comment] 2020-01-22 09:05
@farhatahmad thank you too, i'm ready to test fixes at any time, let me know pls.

**Closed** 2020-03-02 16:49 UTC
Labels: bug, v2.5

**Comment by pshunter** [comment] 2020-12-07 10:02
Hi, FTR my LDAP problem had nothing to do with greenlight. A firewall was blocking large ldap packets due to big user photos because it was suspecting some form of overflow attack.
Thanks for helping to track this down.
